server:
  port: ${GATEWAY_PORT:9000}

spring:
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: ${CLIENT_ADDRESS:http://localhost:4200}
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers: "*"

    zookeeper:
      connect-string: ${ZOOKEEPER_ADDRESS:localhost:2181}
      discovery:
        enabled: true
        register: true